# SPDX-FileCopyrightText: 2020 Free Software Foundation Europe e.V.
#
# SPDX-License-Identifier: CC0-1.0

name: REUSE Compliance Check

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: codeberg-tiny
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v4
      - name: REUSE Compliance Check
        uses: https://github.com/fsfe/reuse-action@v5
